### ISSUE TITLE
Proper defaults if fertility data isn't avaliable 

### ISSUE THREAD

**Issue by AllieDeford** [SCIP-app/androidApp#31]
On the dashboard and the calendar view, fertility information is shown in printed form. If the data is not available for some reason, an appropriate default should be displayed.

**Comment by sindunarasimhan** [comment]
so would that be no value or a string saying "value not available" or something?

**Comment by AllieDeford** [comment]
Something. As long as it's clear. I think right now it just shows the label with nothing or garbage after it. Either hide the fields if it's not available or say something like "value not available"

**Comment by kristindew** [comment]
"data not available" would be more plain language for providers who may encounter this issue
