### ISSUE TITLE
Define behavior for Report a problem and Logout options in navigation drawer

### ISSUE THREAD

**Issue by sindunarasimhan** [SCIP-app/androidApp#33]
I am cleaning up the navigation drawer and I got rid of the HomeScreen option. I have the logout and report a problem options which dont do anything currently. 

Kristin: Will you be able to define the behavior for those? Just add the description to the issues and assign it to me and I will pick it up from there.

**Comment by AllieDeford** [comment]
I'm pretty sure Logout goes to the home screen. @sindunarasimhan

**Comment by kristindew** [comment]
Yeah, logout goes to the home screen and report a problem can be removed - it was an idea for potential future versions of the app when there could be a lot more people using it.
